disabled_rules:
- mark
- comma
- line_length
- opening_brace
- trailing_whitespace
- unused_closure_parameter

opt_in_rules:

included:

excluded:
- Pods
- mytine/Resources/Helper/FMDBManager.swift
- mytine/Sources/Screen/HomeEtc/Model/RootineModel.swift

force_cast: warning # 암시적으로 지정
force_try:
  severity: warning # 명시적으로 지정
